[project]
name = "wanvideo-runpod"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "sky24h", email = "hytian2@gmail.com" },
]
requires-python = ">=3.10,<3.13"

dependencies = [
    "runpod==1.7.10",
    "torch==2.7.0",
    "torchvision==0.22.0",
    "torchaudio==2.7.0",
    "imageio[ffmpeg]==2.37.0",
    "imageio-ffmpeg==0.6.0",
    "safetensors==0.5.2",
    "einops==0.8.1",
    "transformers==4.52.4",
    "accelerate==1.3.0",
    "xformers==0.0.30",
    "diffusers==0.33.1",
    "huggingface-hub==0.32.4",
    "numpy==1.26.4",
    "tokenizers==0.21.0",
    "sentencepiece==0.2.0",
    "tqdm==4.67.1",
    "ftfy==6.3.1",
    "sageattention==1.0.6",
    "opencv-python==4.11.0.86",
]

[tool.ruff]
# Ruff only supports pyproject.toml, not setup.cfg.
# Implicit configurations as default: https://docs.astral.sh/ruff/configuration/
exclude = ["ComfyUI/"]
# Same as MacBookPro (15inch) and IDEs, 1920px full width.
line-length = 144

[tool.ruff.lint]
select = [
    "W",   # pycodestyle warnings
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "S",   # flake8-bandit
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "I",   # isort
    "C90", # mccabe complexity
    "N",   # pep8-naming
    "UP",  # pyupgrade
]
# Allow automatic fixes for all fixable issues
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["S101", "S108"]  # Allow assert and temp file usage in tests
"wan_inference_utils.py" = ["E501"]  # Allow long lines in inference utils due to long example prompts

[tool.ruff.lint.mccabe]
max-complexity = 15  # Increase complexity threshold

[tool.hatch.build.targets.wheel]
packages = ["src/skit"]
